version: "3.9"

services:
  app:
    build: .
    image: node:14
    command: npm run start
    ports: 
      - 5000:5000
    volumes:
      - .:/usr/src/app/
      - /usr/src/app/node_modules
    depends_on:
      - postgres
  
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test
    ports:
      - 5432:5432
    volumes:
      - pg-volume:/var/lib/postgresql/data
  
volumes:
  pg-volume:
    driver: local 